name: Lighthouse Check

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse Check
        uses: foo-software/lighthouse-check-action@v12
        with:
          urls: 'https://timoschreck.github.io/mentalcoach-ts'
          uploadArtifacts: true
